markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: summspider.github.io
title: Summspider's Blog
description: A Smartphone Developer
author: Summspider
email: Summspider#qq.com
github: Summspider

config:
  js_dir:
  img_dir:
  css_dir:
